version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - portfoliodb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev_db
  test_db:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - 5433:5432 # change bind port to 5433
    volumes:
      - portfoliotestdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_db
  cache:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - portfoliocache:/data

  cache-ui:
    image: redislabs/redisinsight
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  portfoliodb:
  portfoliotestdb:
  portfoliocache:
  redisinsight:

