version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - portfoliodb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev_db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  portfoliodb:
